import test from 'node:test';
import assert from 'node:assert/strict';
import { sendNuvemshopPrivacyReport } from '../src/nuvemshopPrivacy.mjs';
import { NUVEMSHOP_REQUIRED_WEBHOOKS, NUVEMSHOP_WEBHOOK_URI } from '../src/nuvemshopOAuth.mjs';
import { createHmac } from 'node:crypto';
import { createNuvemshopOAuthHandler } from '../src/http/oauthNuvemshop.mjs';
import { createNuvemshopWebhookHandler, nuvemshopWebhookDeliveryKey, validateNuvemshopWebhookPayload } from '../src/http/webhookNuvemshop.mjs';
import { sealOAuthSession, openOAuthSession, encryptCommercialSecret } from '../src/commercialOAuthCrypto.mjs';
import { validateNuvemshopReadOnlyApi, stageNuvemshopCredential, reconcileNuvemshopCredential } from '../src/nuvemshopIntegrationSecurity.mjs';
const env={NUVEMSHOP_APP_ID:'41672',NUVEMSHOP_CLIENT_SECRET:'fixture-nuvemshop-secret',COMMERCIAL_OAUTH_ENCRYPTION_KEY:Buffer.alloc(32,21).toString('base64'),NUVEMSHOP_STOREFRONT_URL:'https://zevanory.lojavirtualnuvem.com.br/',DATABASE_URL:'fixture-db',FULFILLMENT_OPERATOR_TOKEN:'fixture-operator-token-that-is-long-enough'};
const token={user_id:123,access_token:'fixture-private-access-token',scope:'read_products,read_orders'};
const response=(status,body)=>new Response(JSON.stringify(body),{status});
function memorySql(){
 const state={sessions:new Map(),pending:new Map(),receipts:new Map(),connections:new Set(['123']),canonical:[],queries:[],revocations:0};
 const sql={state,close:async()=>{},query:async(text,args=[])=>{
  state.queries.push({text,args});
  if(text.startsWith('insert into nuvemshop_oauth_sessions')){state.sessions.set(args[0],{state:args[1],consumed:false});return[{session_hash:args[0]}];}
  if(text.startsWith('update nuvemshop_oauth_sessions')){const row=state.sessions.get(args[0]);if(!row||row.state!==args[1]||row.consumed)return[];row.consumed=true;return[{session_hash:args[0]}];}
  if(text.startsWith('insert into nuvemshop_pending_credentials')){const row={session_hash:args[0],account_id:args[1],access_token_enc:args[2],scope:args[3]};state.pending.set(args[0],row);return[row];}
  if(text.startsWith('select session_hash,account_id'))return state.pending.has(args[0])?[state.pending.get(args[0])]:[];
  if(text.startsWith('insert into provider_oauth_credentials')){state.canonical.push(args);return[{account_id:args[0],expires_at:null}];}
  if(text.startsWith('delete from nuvemshop_pending')){state.pending.delete(args[0]);return[];}
  if(text.startsWith('select outcome'))return state.receipts.has(args[0])?[{outcome:state.receipts.get(args[0]).outcome}]:[];
  if(text.startsWith('select store_id from nuvemshop_connections'))return state.connections.has(args[0])?[{store_id:args[0]}]:[];
  if(text.startsWith('insert into nuvemshop_webhook_receipts')){if(state.receipts.has(args[0]))return[];state.receipts.set(args[0],{store_ref:args[1],event:args[2],outcome:{}});return[{delivery_key:args[0]}];}
  if(text.startsWith('update nuvemshop_webhook_receipts')){state.receipts.get(args[0]).outcome=JSON.parse(args[1]);return[];}
  if(text.startsWith('delete from provider_oauth_credentials')){state.revocations++;return[{account_id:args[0]}];}
  return[];
 }};
 return sql;
}
async function invoke(handler,{method='GET',url='/api/webhooks?provider=nuvemshop_oauth',headers={},rawBody,parsedBody}={}){
 const output={headers:{},statusCode:0};const res={setHeader:(name,value)=>{output.headers[name]=value;},end:body=>{output.statusCode=res.statusCode;output.body=body?JSON.parse(body):null;}};
 await handler({method,url,headers,rawBody,parsedBody},res);return output;
}
async function start(sql,options={}){
 const handler=createNuvemshopOAuthHandler({env,connect:async()=>sql,...options});
 const output=await invoke(handler,{url:'/api/webhooks?provider=nuvemshop_oauth&action=start'});
 assert.equal(output.statusCode,302);const state=new URL(output.headers.location).searchParams.get('state');
 return{handler,state,cookie:output.headers['set-cookie'].split(';')[0],output};
}
function webhookRequest(payload,extra={}){const rawBody=Buffer.from(JSON.stringify(payload));return{method:'POST',url:'/api/webhooks?provider=nuvemshop',rawBody,headers:{'x-linkedstore-hmac-sha256':createHmac('sha256',env.NUVEMSHOP_CLIENT_SECRET).update(rawBody).digest('hex')},...extra};}

test('OAuth start registers durable state and emits secure no-store 302 to the exact app',async()=>{const sql=memorySql();const {output}=await start(sql);assert.equal(new URL(output.headers.location).pathname,'/apps/41672/authorize');assert.match(output.headers['set-cookie'],/HttpOnly; Secure; SameSite=Lax; Path=\/api\/oauth\/nuvemshop; Max-Age=600/);assert.equal(output.headers['cache-control'],'no-store');assert.equal(sql.state.sessions.size,1);});
test('invalid, missing, and tampered OAuth states never exchange a code',async()=>{const sql=memorySql();let exchanges=0;const {handler,state,cookie}=await start(sql,{exchange:async()=>{exchanges++;return token;}});for(const request of [{url:'?code=fixture&state=wrong',headers:{cookie}},{url:'?code=fixture&state='+state,headers:{cookie:cookie+'tampered'}},{url:'?code=fixture',headers:{cookie}},{url:'?code=fixture&code=other&state='+state,headers:{cookie}}]){const out=await invoke(handler,request);assert.equal(out.statusCode,400);assert.equal(out.body.connected,false);}assert.equal(exchanges,0);});
test('concurrent replay can redeem a session only once and never report unvalidated connection',async()=>{const sql=memorySql();let exchanges=0;const {handler,state,cookie}=await start(sql,{exchange:async()=>{exchanges++;return token;},reconcile:async()=>{throw new Error('nuvemshop_api_http_503');}});const req={url:'?code=fixture&state='+state,headers:{cookie}};const results=await Promise.all([invoke(handler,req),invoke(handler,req)]);assert.equal(exchanges,1);assert.deepEqual(results.map(r=>r.statusCode).sort(),[202,400]);assert.ok(results.every(r=>r.body.connected===false));assert.equal(sql.state.pending.size,1);assert.equal(sql.state.canonical.length,0);for(const out of results)assert.match(out.headers['set-cookie'],/Max-Age=0/);assert.ok([...sql.state.pending.values()].every(r=>!r.access_token_enc.includes(token.access_token)));});
test('OAuth does not consume a code while the canonical database is unavailable',async()=>{let exchanges=0;const cookie='zevanory_nuvemshop_oauth='+sealOAuthSession({provider:'nuvemshop',state:'fixture-state'},env);const handler=createNuvemshopOAuthHandler({env,connect:async()=>{throw new Error('private database password');},exchange:async()=>{exchanges++;return token;}});const out=await invoke(handler,{url:'?code=fixture&state=fixture-state',headers:{cookie}});assert.equal(out.statusCode,503);assert.equal(exchanges,0);assert.doesNotMatch(JSON.stringify(out.body),/password/);});
test('missing OAuth secrets fail closed before redirect or provider traffic',async()=>{const out=await invoke(createNuvemshopOAuthHandler({env:{}}),{url:'?action=start'});assert.equal(out.statusCode,503);assert.equal(out.headers.location,undefined);});
test('provider denial clears state without exchanging, and invalid method is rejected',async()=>{const sql=memorySql();const {handler}=await start(sql,{exchange:()=>{throw new Error('unexpected');}});const out=await invoke(handler,{url:'?error=denied-secret'});assert.equal(out.statusCode,400);assert.match(out.headers['set-cookie'],/Max-Age=0/);assert.doesNotMatch(JSON.stringify(out.body),/denied-secret/);assert.equal((await invoke(handler,{method:'POST'})).statusCode,405);});
test('malformed, missing, future, and expired issued-at values cannot bypass session lifetime',()=>{for(const iat of [undefined,'not-a-time',null,Date.now()+60000,Date.now()-600001]){const sealed=encryptCommercialSecret(JSON.stringify({provider:'nuvemshop',state:'fixture',iat}),env);assert.throws(()=>openOAuthSession(sealed,env),/session_expired/);}});
test('operator status/reconciliation refuse unauthenticated callers before database access',async()=>{const handler=createNuvemshopOAuthHandler({env,connect:()=>{throw new Error('unexpected');}});assert.equal((await invoke(handler,{url:'?action=status'})).statusCode,401);assert.equal((await invoke(handler,{method:'POST',url:'?action=reconcile'})).statusCode,401);});
test('read-only proof validates returned store identity and read scopes without customer or order reads',async()=>{const calls=[];const proof=await validateNuvemshopReadOnlyApi({token,env,fetchImpl:async(url,options)=>{calls.push(url);assert.equal(options.method,'GET');assert.equal(options.redirect,'error');assert.ok(options.signal instanceof AbortSignal);return response(200,url.endsWith('/store')?{id:123,original_domain:'zevanory.lojavirtualnuvem.com.br'}:[]);}});assert.equal(proof.store_api,true);assert.equal(proof.products_api,true);assert.equal(proof.webhooks_api,true);assert.equal(calls.length,3);assert.ok(calls.every(u=>!u.includes('/customers')&&!u.includes('/orders')));assert.doesNotMatch(JSON.stringify(proof),/fixture-private-access-token/);});
test('wrong store, missing scopes, and non-array API responses cannot produce proof',async()=>{await assert.rejects(validateNuvemshopReadOnlyApi({token,env,fetchImpl:async()=>response(200,{id:456,original_domain:'another.example'})}),/identity_mismatch/);await assert.rejects(validateNuvemshopReadOnlyApi({token:{...token,scope:'read_products'},env}),/scopes_missing/);await assert.rejects(validateNuvemshopReadOnlyApi({token,env,fetchImpl:async url=>response(200,url.endsWith('/store')?{id:123,original_domain:'zevanory.lojavirtualnuvem.com.br'}:{})}),/products_response_invalid/);});
test('failed API identity leaves encrypted pending token and preserves prior canonical credential',async()=>{const sql=memorySql();sql.state.canonical.push('prior-valid-credential');await stageNuvemshopCredential(sql,{sessionHash:'fixture-session',token,env});await assert.rejects(reconcileNuvemshopCredential(sql,{sessionHash:'fixture-session',env,fetchImpl:async()=>response(200,{id:123,domain:'wrong.example'})}),/identity_mismatch/);assert.deepEqual(sql.state.canonical,['prior-valid-credential']);assert.equal(sql.state.pending.size,1);});
test('HMAC verification precedes processing and parsing uses signed raw body rather than parsedBody',async()=>{const sql=memorySql();const handler=createNuvemshopWebhookHandler({env,connect:async()=>sql});const req=webhookRequest({store_id:123,event:'product/created',id:7},{parsedBody:{store_id:123,event:'app/uninstalled',id:41672}});const out=await invoke(handler,req);assert.equal(out.statusCode,200);assert.equal(out.body.event,'product/created');assert.equal(sql.state.revocations,0);const tampered=await invoke(handler,{...req,rawBody:Buffer.concat([req.rawBody,Buffer.from(' ')])});assert.equal(tampered.statusCode,401);});
test('missing secret, invalid method, unknown event and unsafe IDs fail closed',async()=>{const missing=createNuvemshopWebhookHandler({env:{}});assert.equal((await invoke(missing,{method:'POST'})).statusCode,503);assert.equal((await invoke(missing,{method:'GET'})).statusCode,405);for(const payload of [{store_id:0,event:'product/created',id:1},{store_id:123,event:'invented',id:1},{store_id:Number.MAX_SAFE_INTEGER+1,event:'order/paid',id:1},{store_id:123,event:'app/uninstalled',id:999}])assert.throws(()=>validateNuvemshopWebhookPayload(payload,{env}),/invalid|mismatch/);});
test('signed webhook for another store cannot revoke the configured credential',async()=>{const sql=memorySql();const out=await invoke(createNuvemshopWebhookHandler({env,connect:async()=>sql}),webhookRequest({store_id:456,event:'app/uninstalled',id:41672}));assert.equal(out.statusCode,401);assert.equal(sql.state.revocations,0);assert.equal(sql.state.receipts.size,0);assert.ok(sql.state.queries.some(q=>q.text==='rollback'));});
test('lifecycle duplicate/retry deliveries revoke once and never enable commercial effects',async()=>{const sql=memorySql();const handler=createNuvemshopWebhookHandler({env,connect:async()=>sql});const first=await invoke(handler,webhookRequest({store_id:123,event:'app/uninstalled',id:41672}));const retry=await invoke(handler,webhookRequest({id:41672,retry_count:2,event:'app/uninstalled',store_id:123}));assert.equal(first.body.duplicate,false);assert.equal(retry.body.duplicate,true);assert.equal(sql.state.revocations,1);assert.equal(first.body.commercial_enabled,false);assert.equal(retry.body.commercial_enabled,false);});
test('LGPD payloads without event are handled without storing customer identifiers or raw payloads',async()=>{const sql=memorySql();const handler=createNuvemshopWebhookHandler({env,connect:async()=>sql,sendPrivacyReport:async()=>({merchant_report_sent:true})});for(const payload of [{store_id:123,customer:{id:9,email:'private-customer@example.test'},orders_to_redact:[7]},{store_id:123,customer:{id:9,email:'private-customer@example.test'},data_request:{id:11},orders_requested:[7]}]){const out=await invoke(handler,webhookRequest(payload));assert.equal(out.statusCode,200);assert.equal(out.body.privacy_processed,true);assert.deepEqual(out.body.customer_data,[]);assert.equal(out.body.customer_payloads_stored,false);}const stored=JSON.stringify([...sql.state.receipts.values()]);assert.doesNotMatch(stored,/private-customer|orders_requested|orders_to_redact|"customer"/);});
test('store redaction removes pending and connected store data atomically with credential revocation',async()=>{const sql=memorySql();const out=await invoke(createNuvemshopWebhookHandler({env,connect:async()=>sql}),webhookRequest({store_id:123}));assert.equal(out.statusCode,200);assert.equal(out.body.store_data_redacted,true);assert.equal(out.body.credential_revoked,true);for(const table of ['provider_oauth_credentials','nuvemshop_pending_credentials','nuvemshop_connections','nuvemshop_webhook_receipts'])assert.ok(sql.state.queries.some(q=>q.text.startsWith('delete from '+table)));assert.ok(sql.state.queries.some(q=>q.text==='commit'));});
test('privacy endpoint rejects contradictory event and malformed requests',()=>{assert.throws(()=>validateNuvemshopWebhookPayload({store_id:123,event:'app/store_redact'},{privacyEvent:'customer/redact',env}),/event_invalid/);assert.throws(()=>validateNuvemshopWebhookPayload({store_id:123,customer:{id:9},data_request:{}},{env}),/request_invalid/);assert.throws(()=>validateNuvemshopWebhookPayload({store_id:123,event:'app/store_redact',customer:{id:9}},{env}),/store_invalid/);});
test('deduplication preserves business event timestamps while ignoring delivery retries',()=>{const p={store_id:123,event:'product/updated',id:1,event_launch_ts:100};assert.equal(nuvemshopWebhookDeliveryKey(p,p.event,env.NUVEMSHOP_CLIENT_SECRET),nuvemshopWebhookDeliveryKey({...p,attempt:2},p.event,env.NUVEMSHOP_CLIENT_SECRET));assert.notEqual(nuvemshopWebhookDeliveryKey(p,p.event,env.NUVEMSHOP_CLIENT_SECRET),nuvemshopWebhookDeliveryKey({...p,event_launch_ts:101},p.event,env.NUVEMSHOP_CLIENT_SECRET));});


test('reconciliation persists only after real reads, verified hooks and verified merchant recipient',async()=>{
 const sql=memorySql();await stageNuvemshopCredential(sql,{sessionHash:'fixture-session',token,env});const hooks=[],calls=[];
 const fetchImpl=async(url,options={})=>{calls.push(url);if(url.endsWith('/store'))return response(200,{id:123,original_domain:'zevanory.lojavirtualnuvem.com.br',email:'fixture-merchant@example.test'});if(url.includes('/products'))return response(200,[]);if(options.method==='POST'){hooks.push({...JSON.parse(options.body),id:hooks.length+1});return response(201,hooks.at(-1));}return response(200,hooks);};
 const result=await reconcileNuvemshopCredential(sql,{sessionHash:'fixture-session',env,fetchImpl});assert.equal(result.connected,true);assert.equal(result.webhooks_ready,true);assert.equal(sql.state.pending.size,0);assert.equal(sql.state.canonical.length,1);assert.equal(hooks.length,7);assert.ok(calls.every(u=>u.startsWith('https://api.nuvemshop.com.br/2025-03/123/')));assert.doesNotMatch(JSON.stringify(result),/fixture-private|fixture-merchant/);const owner=sql.state.queries.find(q=>q.text.startsWith('insert into nuvemshop_connections'));assert.doesNotMatch(owner.args[2],/fixture-merchant/);assert.ok(sql.state.queries.some(q=>q.text.includes('pg_advisory_xact_lock')));assert.ok(sql.state.queries.some(q=>q.text.startsWith('delete from nuvemshop_webhook_receipts')));assert.equal(sql.state.queries.at(-1).text,'commit');await assert.rejects(reconcileNuvemshopCredential(sql,{sessionHash:'fixture-session',env,fetchImpl}),/pending_credential_missing/);assert.equal(sql.state.canonical.length,1);
});
test('OAuth staging recovery never returns connected or exposes credentials',async()=>{
 for(const preserved of [true,false]){const sql=memorySql(),baseQuery=sql.query;sql.query=async(q,a)=>{if(q.startsWith('insert into nuvemshop_pending_credentials'))throw new Error('fixture staging failure');return baseQuery(q,a);};let exchanges=0,recoveries=0;const {handler,state,cookie}=await start(sql,{exchange:async()=>{exchanges++;return token;},preserve:async()=>{recoveries++;return{preserved};}});const out=await invoke(handler,{url:'?code=fixture&state='+state,headers:{cookie}});assert.equal(out.statusCode,preserved?202:503);assert.equal(out.body.connected,false);assert.equal(out.body.commercial_enabled,false);assert.equal(exchanges,1);assert.equal(recoveries,1);assert.match(out.headers['set-cookie'],/Max-Age=0/);assert.doesNotMatch(JSON.stringify(out),/fixture-private-access-token/);}
});
test('privacy report is sent only to the encrypted owner verified by store API, with no customer payload',async()=>{
 const privateEnv={...env,RESEND_API_KEY:'fixture-resend-api-key'};const sql={query:async(q,a)=>{assert.equal(a[0],'123');return[{merchant_email_enc:encryptCommercialSecret('fixture-merchant@example.test',env)}];}};let calls=0;const result=await sendNuvemshopPrivacyReport(sql,{storeId:'123',requestId:'11',deliveryKey:'a'.repeat(64),env:privateEnv,fetchImpl:async(url,options)=>{calls++;assert.equal(url,'https://api.resend.com/emails');assert.equal(options.redirect,'error');assert.ok(options.signal instanceof AbortSignal);assert.equal(options.headers['Idempotency-Key'],'nuvemshop-privacy/'+'a'.repeat(64));const body=JSON.parse(options.body);assert.deepEqual(body.to,['fixture-merchant@example.test']);assert.doesNotMatch(body.text,/private-customer|phone|orders_requested/);assert.match(body.text,/"customer_data": \[\]/);return response(200,{id:'fixture-email-id'});}});assert.equal(calls,1);assert.deepEqual(result,{merchant_report_sent:true});assert.doesNotMatch(JSON.stringify(result),/fixture-merchant|fixture-resend/);
});
test('privacy delivery failures are never acknowledged as processed',async()=>{const sql=memorySql();const out=await invoke(createNuvemshopWebhookHandler({env,connect:async()=>sql,sendPrivacyReport:async()=>{throw new Error('private mail provider failure');}}),webhookRequest({store_id:123,customer:{id:9},data_request:{id:11}}));assert.equal(out.statusCode,503);assert.equal(out.body.accepted,false);assert.doesNotMatch(JSON.stringify(out),/private mail/);assert.equal(sql.state.queries.at(-1).text,'rollback');});
test('privacy report rejects missing configuration, missing owner and provider logical error',async()=>{await assert.rejects(sendNuvemshopPrivacyReport({}, {env}),/unconfigured/);await assert.rejects(sendNuvemshopPrivacyReport({query:async()=>[]},{storeId:'123',env:{...env,RESEND_API_KEY:'fixture'}}),/recipient_unverified/);await assert.rejects(sendNuvemshopPrivacyReport({query:async()=>[{merchant_email_enc:encryptCommercialSecret('fixture-merchant@example.test',env)}]},{storeId:'123',requestId:'11',deliveryKey:'a'.repeat(64),env:{...env,RESEND_API_KEY:'fixture'},fetchImpl:async()=>response(200,{error:'logical error'})}),/delivery_failed/);});
test('missing operational event with a resource ID cannot be inferred as store redaction',()=>{assert.throws(()=>validateNuvemshopWebhookPayload({store_id:123,id:7},{env}),/privacy_store_invalid/);});

test('privacy request deduplication uses the provider request identity without customer metadata',()=>{const p={store_id:123,customer:{id:9,email:'private-customer@example.test'},data_request:{id:11}};const key=nuvemshopWebhookDeliveryKey(p,'customers/data_request',env.NUVEMSHOP_CLIENT_SECRET);assert.equal(key,nuvemshopWebhookDeliveryKey({...p,customer:{id:9,email:'changed-customer@example.test'},attempt:2},'customers/data_request',env.NUVEMSHOP_CLIENT_SECRET));assert.notEqual(key,nuvemshopWebhookDeliveryKey({...p,data_request:{id:12}},'customers/data_request',env.NUVEMSHOP_CLIENT_SECRET));assert.notEqual(key,nuvemshopWebhookDeliveryKey({...p,store_id:124},'customers/data_request',env.NUVEMSHOP_CLIENT_SECRET));assert.match(key,/^[a-f0-9]{64}$/);});
