import "jsr:@supabase/functions-js@2.116.0/edge-runtime.d.ts";
const KEY_ID='zev-ai-VFJqId57a0drMaaT';
const PUB='MCowBQYDK2VwAyEA-bc7v7bWx_K-tpkaHsTnBCV7-xvLHXsosJHf9LhKqxA';
const PATH='/functions/v1/arbm-ai-three-provider-probe-20260908';
const te=new TextEncoder();
const b64=(s:string)=>{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0));};
const ub64=(b:Uint8Array)=>btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const sha=async(s:string)=>new Uint8Array(await crypto.subtle.digest('SHA-256',te.encode(s)));
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});
async function verifyRequest(req:Request,raw:string){const kid=req.headers.get('x-zevanory-key-id')||'',ts=req.headers.get('x-zevanory-timestamp')||'',nonce=req.headers.get('x-zevanory-nonce')||'',bh=req.headers.get('x-zevanory-body-sha256')||'',sig=req.headers.get('x-zevanory-signature')||'';if(kid!==KEY_ID)return {ok:false,reason:'key_id'};if(!nonce)return {ok:false,reason:'nonce_missing'};if(!sig)return {ok:false,reason:'signature_missing'};const n=Number(ts);if(!Number.isFinite(n)||Math.abs(Date.now()/1000-n)>120)return {ok:false,reason:'timestamp'};const actual=ub64(await sha(raw));if(actual!==bh)return {ok:false,reason:'body_hash'};const canonical=`v1\n${ts}\n${nonce}\n${bh}\n${PATH}`;try{const key=await crypto.subtle.importKey('spki',b64(PUB),{name:'Ed25519'},false,['verify']);const ok=await crypto.subtle.verify({name:'Ed25519'},key,b64(sig),te.encode(canonical));if(!ok)return {ok:false,reason:'signature'};}catch{return {ok:false,reason:'crypto'}}const url=Deno.env.get('SUPABASE_URL'),svc=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!svc)return {ok:false,reason:'nonce_store_config'};const r=await fetch(url+'/rest/v1/zevanory_ai_gateway_nonces',{method:'POST',headers:{'content-type':'application/json',apikey:svc,authorization:`Bearer ${svc}`,Prefer:'return=minimal'},body:JSON.stringify({nonce,key_id:kid,expires_at:new Date((n+300)*1000).toISOString()})});if(r.status!==201)return {ok:false,reason:r.status===409?'replay':'nonce_store_'+r.status};return {ok:true,reason:'ok'};}
const parse=(t:string)=>{try{return JSON.parse(t)}catch{const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a>=0&&b>a)try{return JSON.parse(t.slice(a,b+1))}catch{};return null}};
async function mistral(systemInstruction:string,input:unknown){const key=Deno.env.get('MISTRAL_API_KEY');if(!key||Deno.env.get('ARBM_MISTRAL_ZERO_SPEND_CONFIRMED')!=='1')throw new Error('mistral_unavailable');const system=(String(systemInstruction||'')+'\nReturn exactly one strict JSON object and no markdown.').slice(0,8000);const user=JSON.stringify(input||{}).slice(0,12000);const r=await fetch('https://api.mistral.ai/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:JSON.stringify({model:'ministral-3b-latest',messages:[{role:'system',content:system},{role:'user',content:user}],response_format:{type:'json_object'},temperature:0,max_tokens:256}),signal:AbortSignal.timeout(12000)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error('mistral_http_'+r.status);const raw=String(j?.choices?.[0]?.message?.content||'');return {provider:'mistral-free',model:j.model||'ministral-3b-latest',decision:parse(raw),http:r.status,content_len:raw.length};}
async function lightning(systemInstruction:string,input:unknown){const stored=String(Deno.env.get('LIGHTNING_API_KEY')||'');const key=stored.split('/')[0];if(!key||Deno.env.get('ARBM_LIGHTNING_ZERO_SPEND_CONFIRMED')!=='1')throw new Error('lightning_unavailable');const system=(String(systemInstruction||'')+'\nReturn exactly one strict JSON object and no markdown.').slice(0,8000);const user=JSON.stringify(input||{}).slice(0,12000);const r=await fetch('https://lightning.ai/api/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:JSON.stringify({model:'lightning-ai/gpt-oss-20b',messages:[{role:'system',content:system},{role:'user',content:user}],temperature:0,max_tokens:256}),signal:AbortSignal.timeout(12000)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error('lightning_http_'+r.status);const raw=String(j?.choices?.[0]?.message?.content||'');return {provider:'lightning-ai-free',model:j.model||'lightning-ai/gpt-oss-20b',decision:parse(raw),http:r.status,content_len:raw.length};}
function authStatus(reason:string){if(reason==='key_id')return 403;if(reason==='timestamp')return 408;if(reason==='body_hash')return 422;if(reason==='signature')return 498;if(reason==='crypto')return 500;if(reason==='replay')return 409;if(reason==='nonce_store_config')return 503;if(reason.startsWith('nonce_store_'))return 424;return 401;}
Deno.serve(async req=>{if(req.method!=='POST')return json({error:'method_not_allowed'},405);const raw=await req.text();const auth=await verifyRequest(req,raw);if(!auth.ok)return json({error:'unauthorized_or_replay',reason:auth.reason},authStatus(auth.reason));let b:any;try{b=JSON.parse(raw)}catch{return json({error:'invalid_json'},400)};if(b?.zero_spend!==true)return json({error:'zero_spend_required'},400);const p=String(b?.provider_hint||'');if(!['mistral','lightning'].includes(p))return json({error:'provider_forbidden'},400);try{const out=p==='mistral'?await mistral(String(b?.systemInstruction||''),b?.input||{}):await lightning(String(b?.systemInstruction||''),b?.input||{});if(!out.decision)return json({error:'invalid_provider_json',provider:out.provider,content_len:out.content_len},502);return json({ok:true,status:'PASS',zero_spend:true,paid_fallback_used:false,...out});}catch(e){return json({ok:false,status:'UNAVAILABLE',zero_spend:true,paid_fallback_used:false,error:String(e?.message||e)},503)}});
