import test from "node:test";import assert from "node:assert/strict";import{readFileSync}from"node:fs";
import {scoreCreative,evaluateCreativeWithRewrites,updateThompsonState,chooseThompsonArm,recordMatureCreativeMetrics,setCreativeAutopublishPaused,creativeAutopublishPaused,recordCreativeEvaluation,renderCreativeAutonomyPage} from "../worker/creative-autonomy.mjs";
const good={creative_id:"c1",brand:"ZEVANORY",site:"zevanory.api.br",width:1080,height:1080,hook:"Organize sua operação com clareza",body:"Automação prática por R$ 197,00. Garantia de 7 dias.",cta:"Conheça a ZEVANORY",price_brl:197};
function kv(){const m=new Map();return{get:async k=>m.get(k)||null,put:async(k,v)=>m.set(k,v),m};}
test("scores every required criterion from 0 to 100 and requires full compliance",()=>{const r=scoreCreative(good);assert.deepEqual(Object.keys(r.criteria),["clarity","single_cta","brand","legibility"]);for(const v of Object.values(r.criteria))assert.ok(v>=0&&v<=100);assert.equal(r.compliance,100);assert.equal(r.score>=85,true);});
test("publishes at 85 with full compliance",()=>{const r=evaluateCreativeWithRewrites(good);assert.equal(r.action,"publish");assert.equal(r.compliance,100);});
test("rewrites at most twice and removes forbidden financial promises",()=>{const r=evaluateCreativeWithRewrites({...good,body:"Ganhe dinheiro grátis",cta:""});assert.ok(r.rewrites<=2);assert.equal(r.action,"publish");assert.doesNotMatch(r.spec.body,/ganhe dinheiro|grátis/i);});
test("discards a creative below 70 without trying to rescue it",()=>{const r=evaluateCreativeWithRewrites({...good,brand:"OTHER",site:"invalid",hook:"x",body:"x",cta:""});assert.equal(r.action,"discard");assert.equal(r.rewrites,0);assert.equal(r.reason,"score_below_70");});
test("kill switch is persisted in KV",async()=>{const store=kv(),env={ZEVANORY_PRIVATE_ARTIFACTS:store};await setCreativeAutopublishPaused(env,true);assert.equal(await creativeAutopublishPaused(env),true);});
test("48h learning updates Thompson arm once and chooses a candidate",async()=>{const store=kv(),env={ZEVANORY_PRIVATE_ARTIFACTS:store},metrics={creative_id:"c1",published_at:new Date(Date.now()-49*3600e3).toISOString(),angle:"proof",format:"square",hour:12,reach:100,saves:3,clicks:5,sales:1};assert.equal((await recordMatureCreativeMetrics(env,metrics)).learned,true);assert.equal((await recordMatureCreativeMetrics(env,metrics)).reason,"already_learned");assert.equal((await recordMatureCreativeMetrics(env,{creative_id:"new",published_at:new Date().toISOString()})).reason,"awaiting_48h");const state=updateThompsonState({},metrics);assert.ok(state.arms["proof|square|12"].alpha>1);assert.ok(chooseThompsonArm(state,[{angle:"proof",format:"square",hour:12}],()=>.5));});
test("private content page shows score, result, performance and kill switch",async()=>{const store=kv(),env={ZEVANORY_PRIVATE_ARTIFACTS:store};await recordCreativeEvaluation(env,{...good,channel:"instagram",score:92,compliance:100,reason:"approved",status:"approved_for_autopublish"});const html=await renderCreativeAutonomyPage(env);assert.match(html,/Conteúdo/);assert.match(html,/Pausar publicação automática/);assert.match(html,/Desempenho/);assert.match(html,/92/);});
test("real worker makes 85/full-compliance the sole creative approval gate",()=>{const source=readFileSync(new URL("../worker/cloudflare-worker.recovered.mjs",import.meta.url),"utf8");assert.match(source,/evaluateCreativeWithRewrites\(spec/);assert.match(source,/const elite2 = autonomy\.action === "publish"/);assert.doesNotMatch(source,/const elite2 = .*min_creative_quality/);assert.match(source,/\/private-api\/creative-autonomy\/pause/);assert.match(source,/sendDailyCreativeReport\(env\)/);assert.match(source,/publicationPaused/);});
