import test from "node:test";import assert from "node:assert/strict";
import {channelChecklist,ensureWeeklyBlog,publishTelegram,publishPinterest,renderBlogArticle,renderChannelsPage,runMultichannelAutonomy} from "../worker/multichannel-autonomy.mjs";
const kv=()=>{const m=new Map();return{m,get:async k=>m.get(k)||null,put:async(k,v)=>m.set(k,v)}};
test("missing credential blocks only its channel and verified channels leave dry_run",()=>{const rows=channelChecklist({META_ACCESS_TOKEN:"x",META_PAGE_ID:"p",INSTAGRAM_BUSINESS_ACCOUNT_ID:"i"});assert.equal(rows.find(x=>x.id==="blog").configured,true);assert.equal(rows.find(x=>x.id==="telegram").mode,"pending");assert.equal(rows.find(x=>x.id==="facebook").mode,"dry_run");const live=channelChecklist({META_ACCESS_TOKEN:"x",META_PAGE_ID:"p",INSTAGRAM_BUSINESS_ACCOUNT_ID:"i",META_APP_LIVE:"true"});assert.equal(live.find(x=>x.id==="facebook").mode,"active");});
test("blog creates all three compliant weekly articles in one cycle with Article, FAQ and UTMs",async()=>{const store=kv(),env={ZEVANORY_PRIVATE_ARTIFACTS:store,PUBLIC_BASE_URL:"https://zevanory.api.br"};const out=await ensureWeeklyBlog(env,new Date("2026-10-07T12:00:00Z"),async()=>({ok:true}));assert.equal(out.total,3);assert.equal(out.created.length,3);const html=await renderBlogArticle(env,out.created[0].id);assert.match(html,/Article/);assert.match(html,/FAQPage/);assert.match(html,/utm_source=blog/);assert.match(html,/Garantia de 7 dias/);});
test("official Telegram and Pinterest adapters return real provider evidence",async()=>{const calls=[];const fetchImpl=async(url,init)=>{calls.push([url,init]);return url.includes("telegram")?{status:200,json:async()=>({ok:true,result:{message_id:7}})}:{status:201,json:async()=>({id:"pin-9"})};};const tg=await publishTelegram({env:{TELEGRAM_BOT_TOKEN:"secret",TELEGRAM_CHANNEL_ID:"@zevanory"},payload:{content:"oi"},fetchImpl});assert.equal(tg.url,"https://t.me/zevanory/7");const pin=await publishPinterest({env:{PINTEREST_ACCESS_TOKEN:"secret",PINTEREST_BOARD_ID:"board"},payload:{title:"t",content:"c",landing_url:"https://zevanory.api.br",media_url:"https://zevanory.api.br/x.png"},fetchImpl});assert.equal(pin.url,"https://www.pinterest.com/pin/pin-9/");assert.equal(calls.length,2);});
test("private Sistema channels checklist contains exact secret names, states and official links",async()=>{const html=await renderChannelsPage({META_ACCESS_TOKEN:"x",META_PAGE_ID:"p",INSTAGRAM_BUSINESS_ACCOUNT_ID:"i"});assert.match(html,/Sistema/);assert.match(html,/TELEGRAM_BOT_TOKEN/);assert.match(html,/YOUTUBE_CLIENT_ID/);assert.match(html,/PINTEREST_ACCESS_TOKEN/);assert.match(html,/Aguardando verificação da empresa \(em análise\)/);assert.match(html,/Pendente credencial/);assert.match(html,/developers\.facebook\.com/);});
test("hourly cycle publishes approved content only to configured channels and persists provider evidence",async()=>{const store=kv();await store.put("zpc:creative-autonomy:feed:v1",JSON.stringify([{creative_id:"c1",status:"approved_for_autopublish",score:91,compliance:100,title:"t",content:"c",asset_url:"https://zevanory.api.br/a.png",landing_url:"https://zevanory.api.br/solucoes"}]));const env={ZEVANORY_PRIVATE_ARTIFACTS:store,TELEGRAM_BOT_TOKEN:"s",TELEGRAM_CHANNEL_ID:"@zevanory"};const out=await runMultichannelAutonomy(env,new Date("2026-10-06T12:00:00Z"),async url=>url.includes("telegram")?{status:200,json:async()=>({ok:true,result:{message_id:9}})}:{status:200,json:async()=>({})});assert.equal(out.evidence.length,1);assert.equal(out.evidence[0].url,"https://t.me/zevanory/9");assert.ok(await store.get("zpc:multichannel:evidence:telegram:c1"));});
test("Telegram automatic publishing is capped at two approved creatives per UTC day",async()=>{const store=kv(),env={ZEVANORY_PRIVATE_ARTIFACTS:store,TELEGRAM_BOT_TOKEN:"s",TELEGRAM_CHANNEL_ID:"@zevanory"};let calls=0;for(let i=1;i<=3;i++){await store.put("zpc:creative-autonomy:feed:v1",JSON.stringify([{creative_id:`c${i}`,status:"approved_for_autopublish",score:91,compliance:100,content:"c",asset_url:"https://zevanory.api.br/a.png"}]));await runMultichannelAutonomy(env,new Date("2026-10-07T12:00:00Z"),async()=>{calls++;return{status:200,json:async()=>({ok:true,result:{message_id:calls}})}});}assert.equal(calls,2);assert.equal(await store.get("zpc:multichannel:quota:telegram:2026-10-07"),"2");});
