import {Pool} from '@neondatabase/serverless';
import {createYouTubeIdentityOAuthStart,readYouTubeIdentityOAuthCookie,exchangeYouTubeIdentityCode,fetchYouTubeIdentity,persistYouTubeIdentityCredential,updateYouTubeCanonicalDescription} from '../youtubeIdentityOAuth.mjs';
const COOKIE='zevanory_youtube_identity_oauth';
const DESCRIPTION='A ZEVANORY é uma empresa de tecnologia, automação e IA aplicada. Criamos e operamos produtos e serviços digitais com foco em execução segura, evidências reais, eficiência e resultados mensuráveis.';
const json=(res,status,body)=>{res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');return res.end(JSON.stringify(body));};
const query=req=>{try{return new URL(req.url||'','https://zevanory.api.br').searchParams}catch{return new URLSearchParams()}};
const cookie=(req,name)=>String(req.headers?.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(`${name}=`))?.slice(name.length+1)||'';
export default async function handler(req,res){
 if(req.method!=='GET')return json(res,405,{error:'method_not_allowed'});const q=query(req),action=String(q.get('action')||'').toLowerCase();
 if(action==='start'){try{const s=createYouTubeIdentityOAuthStart(process.env);res.setHeader('set-cookie',`${COOKIE}=${s.cookie}; HttpOnly; Secure; SameSite=Lax; Path=/api/oauth/youtube; Max-Age=600`);res.statusCode=302;res.setHeader('location',s.url);return res.end();}catch(e){return json(res,503,{provider:'youtube',connected:false,error:String(e.message||'oauth_start_failed')});}}
 const code=String(q.get('code')||'').trim(),state=String(q.get('state')||'').trim(),providerError=String(q.get('error')||'').trim();
 if(!code&&!providerError)return json(res,200,{provider:'youtube',identity_oauth:true,callback_registered:true,authorization_enabled:Boolean(process.env.YOUTUBE_OAUTH_CLIENT_ID&&process.env.YOUTUBE_OAUTH_CLIENT_SECRET)});
 if(providerError)return json(res,400,{provider:'youtube',connected:false,error:'oauth_provider_denied'});
 let pool;try{if(!process.env.DATABASE_URL)throw new Error('database_url_required');readYouTubeIdentityOAuthCookie(cookie(req,COOKIE),state,process.env);const token=await exchangeYouTubeIdentityCode({code,env:process.env});const channel=await fetchYouTubeIdentity(token.access_token);pool=new Pool({connectionString:process.env.DATABASE_URL});const client=await pool.connect();try{await persistYouTubeIdentityCredential({query:(t,a)=>client.query(t,a).then(r=>r.rows)},{token,channelId:channel.id,env:process.env});}finally{client.release();}await updateYouTubeCanonicalDescription({accessToken:token.access_token,channel,description:DESCRIPTION});res.setHeader('set-cookie',`${COOKIE}=; HttpOnly; Secure; SameSite=Lax; Path=/api/oauth/youtube; Max-Age=0`);return json(res,200,{provider:'youtube',connected:true,channel_id:channel.id,title:channel.snippet?.title||null,description_standardized:true,tokens_stored_encrypted:true,commercial_enabled:false});}catch(e){return json(res,503,{provider:'youtube',connected:false,error:String(e.message||'oauth_callback_failed')});}finally{if(pool)await pool.end().catch(()=>{});}
}