import { getYoutubeAccessToken } from "./youtube-access.mjs";
import { readFile } from "node:fs/promises";
const videoPath=process.argv[2];
if(!videoPath)throw new Error("youtube_video_missing");
const accessToken=await getYoutubeAccessToken();
const auth={authorization:`Bearer ${accessToken}`};
const channelResponse=await fetch("https://www.googleapis.com/youtube/v3/channels?part=snippet,contentDetails&mine=true",{headers:auth});const channels=await channelResponse.json().catch(()=>({}));if(!channelResponse.ok||channels.items?.length!==1)throw new Error("youtube_channel_lookup_failed");const channel=channels.items[0];if(String(channel.snippet?.title||"").trim().toUpperCase()!=="ZEVANORY")throw new Error("youtube_channel_title_mismatch");
const title="ZEVANORY Short · IA prática com clareza";const metadata={snippet:{title,description:"IA prática para organizar tarefas repetitivas com clareza. Garantia de 7 dias. Saiba mais: https://zevanory.api.br/material-gratuito?utm_source=youtube&utm_medium=organic&utm_campaign=short_ia_pratica",tags:["ZEVANORY","IA prática","automação"],categoryId:"27"},status:{privacyStatus:"private",selfDeclaredMadeForKids:false}};
const start=await fetch("https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status",{method:"POST",headers:{...auth,"content-type":"application/json; charset=utf-8","x-upload-content-type":"video/mp4"},body:JSON.stringify(metadata)});if(!start.ok||!start.headers.get("location"))throw new Error("youtube_resumable_start_failed");const bytes=await readFile(videoPath);const uploaded=await fetch(start.headers.get("location"),{method:"PUT",headers:{...auth,"content-type":"video/mp4","content-length":String(bytes.length)},body:bytes});const video=await uploaded.json().catch(()=>({}));if(!uploaded.ok||!video.id)throw new Error("youtube_upload_failed");
const evidence={channel:"youtube",provider_post_id:String(video.id),url:`https://www.youtube.com/watch?v=${video.id}`,publishedAt:new Date().toISOString()};
const cert=String(process.env.CERTIFICATION_E2E_TOKEN||"");if(!cert)throw new Error("certification_token_missing");
const recorded=await fetch("https://zevanory.api.br/api/internal/channels/evidence",{method:"POST",headers:{"content-type":"application/json","x-certification-e2e-token":cert},body:JSON.stringify(evidence)});if(!recorded.ok)throw new Error("youtube_evidence_record_failed");
console.log(JSON.stringify({channelId:channel.id,title:channel.snippet.title,videoId:video.id,privacyStatus:video.status?.privacyStatus||"private",url:evidence.url}));
