const base='https://zevanory.api.br';
const slugs=['solucoes','arbm-sist','ia-na-pratica','vendas-na-pratica','lucro-e-caixa','combo-ia-vendas','negocio-completo'];
const checks=[]; const add=(id,name,pass,evidence='')=>checks.push({id,name,pass:Boolean(pass),evidence});
const sitemap=await (await fetch(base+'/sitemap.xml')).text();
const robots=await (await fetch(base+'/robots.txt')).text();
const release=await (await fetch(base+'/api/release')).json();
const pages={}; for(const s of slugs){const r=await fetch(base+'/'+s);pages[s]={status:r.status,html:await r.text()};}
add(1,'sitemap responde',sitemap.includes('<urlset'));
add(2,'robots responde',robots.includes('User-agent'));
add(3,'robots libera crawling',/Allow:\s*\//.test(robots));
add(4,'robots referencia sitemap',robots.includes(base+'/sitemap.xml'));
add(5,'sitemap inclui home',sitemap.includes('<loc>'+base+'/</loc>'));
add(6,'sitemap inclui solucoes',sitemap.includes(base+'/solucoes'));
add(7,'sitemap inclui ARBM SIST',sitemap.includes(base+'/arbm-sist'));
add(8,'sitemap inclui 5 produtos',slugs.slice(2).every(s=>sitemap.includes(base+'/'+s)));
add(9,'todas paginas HTTP 200',slugs.every(s=>pages[s].status===200));
add(10,'nenhuma pagina vazia',slugs.every(s=>pages[s].html.length>500));for(const [i,s] of slugs.entries()) add(11+i,'title '+s,/<title>[^<]{8,}<\/title>/i.test(pages[s].html));
add(18,'descriptions completas',slugs.every(s=>/<meta name="description" content="[^"]{30,}"/i.test(pages[s].html)));
add(19,'canonicals completos',slugs.every(s=>pages[s].html.includes(`rel="canonical" href="${base}/${s}"`)));
add(20,'Open Graph title',slugs.every(s=>/property="og:title"/i.test(pages[s].html)));
add(21,'Open Graph description',slugs.every(s=>/property="og:description"/i.test(pages[s].html)));
add(22,'Open Graph URL',slugs.every(s=>/property="og:url"/i.test(pages[s].html)));
add(23,'Open Graph image',slugs.every(s=>/property="og:image"/i.test(pages[s].html)));
add(24,'Twitter card',slugs.every(s=>/name="twitter:card"/i.test(pages[s].html)));
add(25,'JSON-LD',slugs.every(s=>/application\/ld\+json/i.test(pages[s].html)));
add(26,'H1 unico presente',slugs.every(s=>(pages[s].html.match(/<h1\b/gi)||[]).length===1));
add(27,'lang pt-BR',slugs.every(s=>/html lang="pt-BR"/i.test(pages[s].html)));
add(28,'viewport mobile',slugs.every(s=>/name="viewport"/i.test(pages[s].html)));
add(29,'favicon',slugs.every(s=>/rel="icon"/i.test(pages[s].html)));
add(30,'links internos solucoes',slugs.every(s=>pages[s].html.includes('/solucoes')));
add(31,'sem GIRO LOCAL',slugs.every(s=>!/GIRO LOCAL/i.test(pages[s].html)));
add(32,'marca ZEVANORY presente',slugs.every(s=>/ZEVANORY/i.test(pages[s].html)));
add(33,'CTA sem compra publica',slugs.every(s=>!/Comprar agora|Finalizar compra/i.test(pages[s].html)));
add(34,'gate comercial explicito',slugs.every(s=>/gate|disponibilidade comercial|venda/i.test(pages[s].html)));
add(35,'sem promessa garantida',slugs.every(s=>!/resultado garantido|100% garantido/i.test(pages[s].html)));add(36,'sales globally blocked',release.sales_mode==='globally-blocked');
add(37,'checkout globally blocked',release.checkout_mode==='globally-blocked');
add(38,'financial disabled',release.financial_mode==='disabled');
add(39,'whatsapp disabled',release.whatsapp_mode==='disabled');
add(40,'quality gate approved',release.assurance?.quality_gate==='approved');
add(41,'security approved',release.assurance?.security_10x==='approved');
add(42,'observability approved',release.assurance?.observability_10x==='approved');
add(43,'architecture approved',release.assurance?.architecture_20x==='approved');
add(44,'official brand approved',release.assurance?.official_brand==='approved');
const key='f9c014c1ea7ab785ce3fafdca205636b'; const kr=await fetch(base+'/'+key+'.txt');
add(45,'IndexNow key publicado',kr.status===200 && (await kr.text()).trim()===key);
add(46,'sitemap tem 12 URLs',(sitemap.match(/<loc>/g)||[]).length===12);
add(47,'solucoes referencia ARBM SIST',pages.solucoes.html.includes('/arbm-sist'));
add(48,'solucoes referencia 5 produtos',slugs.slice(2).every(s=>pages.solucoes.html.includes('/'+s)));
add(49,'ARBM SIST schema software',/"@type":"SoftwareApplication"/.test(pages['arbm-sist'].html));
add(50,'zero falha nos 49 anteriores',checks.every(x=>x.pass));
for(const x of checks) console.log(`${x.id.toString().padStart(2,'0')} ${x.pass?'PASS':'FAIL'} ${x.name}`);
const failed=checks.filter(x=>!x.pass); console.log(`AUDIT50 total=${checks.length} pass=${checks.length-failed.length} fail=${failed.length}`); if(failed.length)process.exit(1);