import { readFile, access } from 'node:fs/promises';
import { RELEASE } from '../src/release.mjs';
import { REQUIRED_TABLES, REQUIRED_MIGRATIONS } from '../src/schemaHealth.mjs';
const root=new URL('../',import.meta.url); const checks=[];
const text=async p=>readFile(new URL(p,root),'utf8');
const exists=async p=>{try{await access(new URL(p,root));return true}catch{return false}};
const add=(name,ok)=>checks.push({name,ok:Boolean(ok)});
const env=await text('.env.example'); const pkg=JSON.parse(await text('package.json')); const workflow=await text('.github/workflows/quality.yml');
add('01 final release',RELEASE.id==='ZEVANORY-EG0039-FINAL');
add('02 required schema tables',REQUIRED_TABLES.length>=23&&['integration_outbox','agent_jobs','agent_runs','agent_memory','agent_control_state','agent_approvals','customer_lifecycle_profiles','customer_lifecycle_events','attribution_touchpoints','lifecycle_evidence_events','lifecycle_certification_artifacts','certification_pilot_invites','intelligence_snapshots'].every(x=>REQUIRED_TABLES.includes(x)));
add('03 required migrations',REQUIRED_MIGRATIONS.length>=16&&REQUIRED_MIGRATIONS.includes('010_payment_provider_abstraction')&&REQUIRED_MIGRATIONS.includes('011_agent_control_and_trace')&&REQUIRED_MIGRATIONS.includes('012_sales_lifecycle_v2')&&REQUIRED_MIGRATIONS.includes('015_lifecycle_certification_provenance')&&REQUIRED_MIGRATIONS.includes('016_certification_pilot')&&REQUIRED_MIGRATIONS.includes('024_market_product_intelligence'));
add('04 CRM engine',await exists('src/salesPipeline.mjs')); add('05 follow-up engine',(await text('src/salesPipeline.mjs')).includes('buildFollowUpPlan'));
add('06 unit economics',await exists('src/unitEconomics.mjs')); add('07 learning engine',await exists('src/learningEngine.mjs'));
add('08 autonomous revenue agent',await exists('src/revenueAgent.mjs')&&await exists('src/agentWorker.mjs'));
add('09 enterprise assurance',await exists('src/enterpriseAssurance.mjs')&&await exists('src/http/assurance.mjs'));
add('10 provider contract registry',await exists('src/providerContracts.mjs'));
add('11 secret scan',pkg.scripts['supplychain:scan']==='node scripts/secret-scan.mjs');
add('12 contract smoke',pkg.scripts['contract:smoke']==='node scripts/contract-smoke.mjs');
add('13 load smoke',pkg.scripts['load:smoke']==='node scripts/load-smoke.mjs');
add('14 SLO policy',await exists('specs/SLO_POLICY.md'));
add('15 enterprise activation offer and rules audits in CI',workflow.includes('npm run audit:enterprise:10x')&&workflow.includes('npm run audit:activation:20x')&&workflow.includes('npm run audit:offer:20x')&&workflow.includes('npm run audit:rules:20x'));
add('16 activation route required',RELEASE.requiredRoutes.includes('/api/activation/readiness')&&await exists('api/config.mjs'));
add('17 sales globally off',env.includes('SALE_GLOBALLY_ENABLED=false')&&!env.includes('SALE_GLOBALLY_ENABLED=true'));
add('18 checkout and financial off',env.includes('CHECKOUT_ENABLED=false')&&env.includes('FINANCIAL_EVENTS_ENABLED=false'));
add('19 WhatsApp sales off',env.includes('WHATSAPP_SALES_ENABLED=false')); add('20 DR remains rollback only',RELEASE.recovery.persistent_changes===false);
for(const c of checks) console.log(`${c.ok?'APPROVED':'FAILED'} ${c.name}`);
const failed=checks.filter(c=>!c.ok); console.log(`AUDIT_FINAL_${failed.length?'BLOCKED':'APPROVED'} units=${checks.length} approved=${checks.length-failed.length} failed=${failed.length}`); if(failed.length) process.exit(1);
