import { readFile, access } from 'node:fs/promises';
import { RELEASE } from '../src/release.mjs';
const root=new URL('../',import.meta.url);
const text=async p=>readFile(new URL(p,root),'utf8');
const exists=async p=>{try{await access(new URL(p,root));return true}catch{return false}};
const checks=[]; const add=(name,ok)=>checks.push({name,ok:Boolean(ok)});
const pkg=JSON.parse((await text('package.json')).replace(/^\uFEFF/,''));
const vercel=JSON.parse((await text('vercel.json')).replace(/^\uFEFF/,''));
const env=await text('.env.example'); const agents=await text('AGENTS.md');
const scope=await text('specs/SCOPE_BOUNDARY.md'); const master=await text('ZEVANORY_MASTER.md');
const audit3x=await text('validation/AUDIT-3X-CURRENT.json');
add('01 canonical package',pkg.name==='zevanory');
add('02 canonical scope',scope.includes('C:\\Sistemas\\ZEVANORY'));
add('03 agent canonical entry',agents.includes('ZEVANORY_MASTER.md'));
add('04 production domain',env.includes('PUBLIC_BASE_URL=https://zevanory.api.br'));
add('05 sale switch off',env.includes('SALE_GLOBALLY_ENABLED=false'));
add('06 pre-sale switch off',env.includes('PRE_SALE_GATES_APPROVED=false'));
add('07 checkout switch off',env.includes('CHECKOUT_ENABLED=false'));
add('08 whatsapp switch off',env.includes('WHATSAPP_SALES_ENABLED=false'));
add('09 financial switch off',env.includes('FINANCIAL_EVENTS_ENABLED=false'));
add('10 release FINAL',RELEASE.id==='ZEVANORY-EG0038-FINAL');
add('11 health required route',RELEASE.requiredRoutes.includes('/api/health'));
add('12 assurance required route',RELEASE.requiredRoutes.includes('/api/assurance'));
add('13 health api exists',await exists('api/health.mjs'));
add('14 assurance api exists',await exists('api/assurance.mjs'));
add('15 runbook current', (await text('RUNBOOK-OPERACIONAL.md')).includes('15 tabelas e migrations 001-009'));
const headers=Object.fromEntries(vercel.headers[0].headers.map(x=>[x.key,x.value]));
add('16 strict CSP',Boolean(headers['Content-Security-Policy']));
add('17 browser hardening',headers['X-Content-Type-Options']==='nosniff'&&headers['X-Frame-Options']==='DENY');
add('18 permissions policy',Boolean(headers['Permissions-Policy']));
add('19 cross-origin isolation',Boolean(headers['Cross-Origin-Opener-Policy'])&&Boolean(headers['Cross-Origin-Resource-Policy']));
add('20 referrer and dns policy',Boolean(headers['Referrer-Policy'])&&headers['X-DNS-Prefetch-Control']==='off');
add('21 root route',vercel.rewrites.some(x=>x.source==='/'&&x.destination==='/public/index.html'));
add('22 pilot route',vercel.rewrites.some(x=>x.source==='/piloto'));
add('23 events route',vercel.rewrites.some(x=>x.source==='/api/events/public'));
add('24 enterprise SLO policy',await exists('specs/SLO_POLICY.md'));
add('25 audit3x record',audit3x.includes('"failed": 0'));
add('26 master canonical',master.includes('DOCUMENTO MESTRE CANONICO'));
add('27 complete quality gates',pkg.scripts?.['audit:enterprise:10x']==='node scripts/audit-enterprise-10x.mjs'&&pkg.scripts?.['contract:smoke']==='node scripts/contract-smoke.mjs');
add('28 no checkout activation',!env.includes('CHECKOUT_ENABLED=true'));
add('29 no whatsapp activation',!env.includes('WHATSAPP_SALES_ENABLED=true'));
add('30 no financial activation',!env.includes('FINANCIAL_EVENTS_ENABLED=true'));
for(const r of checks) console.log(`${r.ok?'APPROVED':'FAILED'} ${r.name}`);
const failed=checks.filter(r=>!r.ok);
console.log(`AUDIT_30X_${failed.length?'BLOCKED':'APPROVED'} units=${checks.length} approved=${checks.length-failed.length} failed=${failed.length}`);
if(failed.length) process.exit(1);
