import { readFile, access } from 'node:fs/promises';
import { RELEASE } from '../src/release.mjs';
import { REQUIRED_TABLES, REQUIRED_MIGRATIONS } from '../src/schemaHealth.mjs';
const root=new URL('../',import.meta.url); const checks=[];
const text=async p=>readFile(new URL(p,root),'utf8');
const exists=async p=>{try{await access(new URL(p,root));return true}catch{return false}};
const add=(name,ok)=>checks.push({name,ok:Boolean(ok)});
const env=await text('.env.example'); const pkg=JSON.parse(await text('package.json'));
const market=await text('specs/MARKET_PARAMETERS.md');
const workflow=await text('.github/workflows/quality.yml');
add('01 final release',RELEASE.id==='ZEVANORY-EG0032-FINAL');
add('02 seven required tables',REQUIRED_TABLES.length===7&&REQUIRED_TABLES.includes('sales_leads')&&REQUIRED_TABLES.includes('sales_actions')&&REQUIRED_TABLES.includes('unit_economics_snapshots'));
add('03 six migrations',REQUIRED_MIGRATIONS.length===6&&REQUIRED_MIGRATIONS.includes('006_sales_machine'));
add('04 CRM engine',await exists('src/salesPipeline.mjs'));
add('05 follow-up engine',(await text('src/salesPipeline.mjs')).includes('buildFollowUpPlan'));
add('06 unit economics',await exists('src/unitEconomics.mjs'));
add('07 learning engine',await exists('src/learningEngine.mjs'));add('08 sourced market parameters',market.includes('HubSpot')&&market.includes('Baymard')&&market.includes('Google'));
add('09 resilience gate',pkg.scripts['resilience:smoke']==='node scripts/resilience-smoke.mjs');
add('10 sales audit gate',pkg.scripts['audit:sales:20x']==='node scripts/audit-sales-machine-20x.mjs');
add('11 CI quality gate',workflow.includes('npm run audit:final')&&workflow.includes('npm run audit:sales:20x'));
add('12 final evidence',await exists('evidence/EG-0032-sales-machine-final.md'));
add('13 sales globally off',env.includes('SALE_GLOBALLY_ENABLED=false')&&!env.includes('SALE_GLOBALLY_ENABLED=true'));
add('14 checkout and financial off',env.includes('CHECKOUT_ENABLED=false')&&env.includes('FINANCIAL_EVENTS_ENABLED=false'));
add('15 WhatsApp sales off',env.includes('WHATSAPP_SALES_ENABLED=false'));
for(const c of checks) console.log(`${c.ok?'APPROVED':'FAILED'} ${c.name}`);
const failed=checks.filter(c=>!c.ok);
console.log(`AUDIT_FINAL_${failed.length?'BLOCKED':'APPROVED'} units=${checks.length} approved=${checks.length-failed.length} failed=${failed.length}`);
if(failed.length) process.exit(1);