import { readFile, access } from 'node:fs/promises';
import { RELEASE } from '../src/release.mjs';
import { REQUIRED_TABLES, REQUIRED_MIGRATIONS } from '../src/schemaHealth.mjs';
const root=new URL('../',import.meta.url); const checks=[];
const text=async p=>readFile(new URL(p,root),'utf8');
const exists=async p=>{try{await access(new URL(p,root));return true}catch{return false}};
const add=(name,ok)=>checks.push({name,ok:Boolean(ok)});
const env=await text('.env.example'); const pkg=JSON.parse(await text('package.json')); const workflow=await text('.github/workflows/quality.yml');
add('01 final release',RELEASE.id==='ZEVANORY-EG0036-FINAL');
add('02 fifteen required tables',REQUIRED_TABLES.length===15&&REQUIRED_TABLES.includes('agent_jobs')&&REQUIRED_TABLES.includes('knowledge_documents'));
add('03 nine migrations',REQUIRED_MIGRATIONS.length===9&&REQUIRED_MIGRATIONS.includes('008_autonomous_revenue_engine')&&REQUIRED_MIGRATIONS.includes('009_composable_infrastructure'));
add('04 CRM engine',await exists('src/salesPipeline.mjs')); add('05 follow-up engine',(await text('src/salesPipeline.mjs')).includes('buildFollowUpPlan'));
add('06 unit economics',await exists('src/unitEconomics.mjs')); add('07 learning engine',await exists('src/learningEngine.mjs'));
add('08 autonomous revenue agent',await exists('src/revenueAgent.mjs')&&await exists('src/agentWorker.mjs'));
add('09 Gemini adapter with deterministic fallback',(await text('src/aiProvider.mjs')).includes('gemini-3.7-flash')&&(await text('src/aiProvider.mjs')).includes('deterministicDecision'));
add('10 tool risk policy',await exists('src/agentPolicy.mjs')); add('11 agent eval gate',await exists('src/agentEvals.mjs'));
add('12 channel adapter registry',await exists('src/channelAdapters.mjs')); add('13 knowledge engine',await exists('src/knowledgeEngine.mjs'));
add('14 migration 008 gate',pkg.scripts['migration:008']==='node --env-file-if-exists=.env.production.local scripts/apply-migration-008.mjs');
add('15 autonomous engine audit in CI',workflow.includes('npm run audit:engine:20x'));
add('16 worker routes required',RELEASE.requiredRoutes.includes('/api/agent/run')&&RELEASE.requiredRoutes.includes('/api/agent/status'));
add('17 sales globally off',env.includes('SALE_GLOBALLY_ENABLED=false')&&!env.includes('SALE_GLOBALLY_ENABLED=true'));
add('18 checkout and financial off',env.includes('CHECKOUT_ENABLED=false')&&env.includes('FINANCIAL_EVENTS_ENABLED=false'));
add('19 WhatsApp sales off',env.includes('WHATSAPP_SALES_ENABLED=false')); add('20 DR remains rollback only',RELEASE.recovery.persistent_changes===false);
for(const c of checks) console.log(`${c.ok?'APPROVED':'FAILED'} ${c.name}`);
const failed=checks.filter(c=>!c.ok); console.log(`AUDIT_FINAL_${failed.length?'BLOCKED':'APPROVED'} units=${checks.length} approved=${checks.length-failed.length} failed=${failed.length}`); if(failed.length) process.exit(1);
