import { readFile, access } from 'node:fs/promises';
import { RELEASE } from '../src/release.mjs';
import { buildSystemHealth } from '../src/systemHealth.mjs';
const root=new URL('../',import.meta.url);
const text=async p=>readFile(new URL(p,root),'utf8');
const exists=async p=>{try{await access(new URL(p,root));return true}catch{return false}};
const checks=[]; const add=(name,ok)=>checks.push({name,ok:Boolean(ok)});
const pkg=JSON.parse((await text('package.json')).replace(/^\uFEFF/,''));
const vercel=JSON.parse((await text('vercel.json')).replace(/^\uFEFF/,''));
const env=await text('.env.example'); const agents=await text('AGENTS.md');
const scope=await text('specs/SCOPE_BOUNDARY.md'); const runbook=await text('RUNBOOK-OPERACIONAL.md');
const master=await text('ZEVANORY_MASTER.md'); const healthApi=await text('api/health.mjs');
const audit3x=await text('validation/AUDIT-3X-CURRENT.json');
add('01 canonical package',pkg.name==='zevanory');
add('02 canonical scope',scope.includes('C:\\Sistemas\\ZEVANORY'));
add('03 agent canonical entry',agents.includes('ZEVANORY_MASTER.md'));
add('04 production domain',env.includes('PUBLIC_BASE_URL=https://zevanory.api.br'));
add('05 sale switch off',env.includes('SALE_GLOBALLY_ENABLED=false'));
add('06 pre-sale switch off',env.includes('PRE_SALE_GATES_APPROVED=false'));
add('07 checkout switch off',env.includes('CHECKOUT_ENABLED=false'));
add('08 whatsapp switch off',env.includes('WHATSAPP_SALES_ENABLED=false'));
add('09 financial switch off',env.includes('FINANCIAL_EVENTS_ENABLED=false'));
add('10 release EG0027',RELEASE.id==='ZEVANORY-EG0027-RC1');
add('11 health required route',RELEASE.requiredRoutes.includes('/api/health'));
add('12 health api exists',await exists('api/health.mjs'));
add('13 health core exists',await exists('src/systemHealth.mjs'));
add('14 runbook exists',await exists('RUNBOOK-OPERACIONAL.md'));
add('15 runbook rollback',runbook.includes('Recuperação e rollback'));
const headers=Object.fromEntries(vercel.headers[0].headers.map(x=>[x.key,x.value])); 
add('16 nosniff',headers['X-Content-Type-Options']==='nosniff'); 
add('17 frame deny',headers['X-Frame-Options']==='DENY'); 
add('18 permissions policy',headers['Permissions-Policy']==='camera=(), microphone=(), geolocation=()');
add('19 opener policy',headers['Cross-Origin-Opener-Policy']==='same-origin');
add('20 referrer policy',headers['Referrer-Policy']==='strict-origin-when-cross-origin');
add('21 root route',vercel.rewrites.some(x=>x.source==='/'&&x.destination==='/public/index.html'));
add('22 pilot route',vercel.rewrites.some(x=>x.source==='/piloto'));
add('23 events route',vercel.rewrites.some(x=>x.source==='/api/events/public'));
add('24 evidence EG0027',await exists('evidence/EG-0027-structure-health-hardening.md'));
add('25 audit3x record',audit3x.includes('AUDIT_3X_APPROVED')||audit3x.includes('"failed": 0'));
add('26 master canonical',master.includes('DOCUMENTO MESTRE CANONICO'));
add('27 scope root',scope.includes('C:\\Sistemas\\ZEVANORY'));
add('28 no checkout activation',!env.includes('CHECKOUT_ENABLED=true'));
add('29 no whatsapp activation',!env.includes('WHATSAPP_SALES_ENABLED=true'));
add('30 no financial activation',!env.includes('FINANCIAL_EVENTS_ENABLED=true'));
for(const r of checks) console.log(`${r.ok?'APPROVED':'FAILED'} ${r.name}`);
const failed=checks.filter(r=>!r.ok);
console.log(`AUDIT_30X_${failed.length?'BLOCKED':'APPROVED'} units=${checks.length} approved=${checks.length-failed.length} failed=${failed.length}`);
if(failed.length) process.exit(1);
