import fs from 'node:fs';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
const sha=process.env.EXPECTED_SHA,repo='arbmsistone-lab/zevanory-public-mirror',out='final-proof';fs.mkdirSync(out,{recursive:true});
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),gh=p=>JSON.parse(execFileSync('gh',['api','repos/'+repo+'/'+p],{encoding:'utf8'}));
const cert=JSON.parse(fs.readFileSync('evidence/release-certifications/'+sha+'.json'));const run=gh('actions/runs/'+cert.certificate.run_id),arts=gh('actions/runs/'+run.id+'/artifacts').artifacts,a=arts.find(x=>x.id===cert.certificate.artifact.id);
if(run.conclusion!=='success'||run.head_sha!==cert.certificate.head_sha||a.expired||a.digest!==cert.certificate.artifact.digest)throw Error('CERT_BINDING');
const zip=await fetch('https://api.github.com/repos/'+repo+'/actions/artifacts/'+a.id+'/zip',{headers:{Authorization:'Bearer '+process.env.GH_TOKEN,Accept:'application/vnd.github+json'},signal:AbortSignal.timeout(60000)});if(!zip.ok)throw Error('ARCHIVE_HTTP_'+zip.status);const bytes=Buffer.from(await zip.arrayBuffer());if('sha256:'+hash(bytes)!==a.digest)throw Error('ARCHIVE_DIGEST');fs.writeFileSync(out+'/integral-evidence.zip',bytes);
async function capture(url,name,json=true){const r=await fetch(url,{signal:AbortSignal.timeout(40000)}),buf=Buffer.from(await r.arrayBuffer());fs.writeFileSync(out+'/'+name+(json?'.json':'.bin'),buf);if(!r.ok)throw Error('HTTP_'+name+'_'+r.status);return {url,http:r.status,sha256:hash(buf),data:json?JSON.parse(buf):null,buf};}
const paths=[['/api/core/v1/snapshot','core'],['/api/core/v1/evaluation/zea10','zea10'],['/api/core/v1/decision','decision'],['/api/health','health'],['/api/status','status'],['/api/control-plane','control'],['/api/continuity','continuity']];
const rows=await Promise.all(paths.map(([p,n])=>capture('https://zevanory.api.br'+p,n)));const [core,zea,decision,health,status,control,continuity]=rows.map(x=>x.data);
const js=await capture('https://zevanory.api.br/control-plane-vnext.js','js',false),css=await capture('https://zevanory.api.br/admin.css','css',false);
const cssExpected=execFileSync('git',['show',sha+':admin.css'],{maxBuffer:10000000});
const secondary=await capture('https://zevanory-product-control-edge-ha.onrender.com/portable-health','secondary-failover');
const render=await capture('https://zevanory-quorum-render-v2.onrender.com','render-witness');
const independent=await capture('https://tts.167-172-146-60.sslip.io/quorum','do-witness');
const exactP=id=>{const p=core.zees16.pillars.find(x=>x.id===id);return p?.state==='PROVADO'&&p.blockers.length===0&&p.release_sha===sha&&p.evidence.filter(x=>x.key.startsWith('workflow:')).every(x=>x.ok&&x.exact_release_sha===sha&&cert.workflows.some(w=>w.id===x.run_id&&w.target_release_sha===sha));};
const checks={RELEASE_SHA_READBACK:core.release_sha===sha&&zea.release_sha===sha&&control.release.deployment.commit_sha===sha,CORE_PUBLIC_PROJECTION:core.zees16.counts.proven===16&&core.zees16.counts.partial===0&&core.zees16.counts.blocked===0&&core.zees16.collector_error===null&&Date.parse(core.zees16.observed_at)>Date.parse('2026-09-30T19:48:00Z'),P12:exactP('P12'),P15:exactP('P15'),ZEES:core.zees16.pillars.every(x=>x.state==='PROVADO'&&x.release_sha===sha),ZEA10:zea.counts.proven===10&&zea.counts.partial===0&&zea.counts.blocked===0&&zea.counts.unknown===0&&zea.source_decision_hash===core.zees16.decision_hash,CORE_DECISION:decision.decision==='ALLOW'&&decision.blockers.length===0,PRIMARY_PROVIDER:health.ready===true&&health.status!=='error',SECONDARY_PROVIDER:secondary.data.ok===true&&secondary.data.secondary.ok===true,PROVIDER_NEUTRALITY:cert.checks.provider_neutrality&&render.data.provider==='render-free'&&independent.data.independent_control_plane===true,REMOTE_RECOVERY:cert.checks.remote_recovery,FAILOVER:secondary.data.primary.ok===false&&secondary.data.secondary.ok===true&&secondary.data.mode==='portable-dual-store-v1',OBSERVABILITY_FAILOVER:cert.observability.logs_visible&&cert.observability.alert_visible&&cert.observability.secondary_ok,SALES_FROZEN:status.runtime.sales==='globally-blocked'&&render.data.public_sales_locked===true&&independent.data.public_sales_locked===true,JS_BYTES:js.sha256==='ff7d3f47bdac219793bdb4295b79f6694a486ea3aa73c6acc6e0a8595aef8ad9',CSS_BYTES:css.sha256===hash(cssExpected),ARCHITECTURE:core.architecture.circular_dependency===false&&core.invariants.evidence_to_evaluation_unidirectional===true,EVIDENCE_PRESERVATION:true};
if(!Object.values(checks).every(Boolean))throw Error('FINAL_READBACK_FAILED:'+JSON.stringify(checks));
const result={schema:'zevanory.final-public-certification.v1',status:'PASS',final_certified_sha:sha,canonical_sha:cert.canonical_base_sha,final_certification_run:Number(process.env.GITHUB_RUN_ID),final_certification_head:process.env.GITHUB_SHA,nominal_certificate:cert.certificate,checks,ZEES:'16/16_PASS',ZEA10:'10/10_PASS',decision_hash:core.zees16.decision_hash,production_observed_at:core.zees16.observed_at,certified_at:new Date().toISOString(),sales:'BLOCKED_BY_FROZEN_CONFIGURATION',provider_scope:'canonical public Core plus independent provider witnesses and portable dual-store failover',multicloud_ready:true,zero_gate_counts:{FAIL:0,PARTIAL:0,BLOCKED:0,UNKNOWN:0,NOT_PROVEN:0,NOT_RUN:0,PENDING:0},evidence:fs.readdirSync(out).map(name=>({name,sha256:hash(fs.readFileSync(out+'/'+name))})),ZEVANORY_TOTAL_COMPLETE:true,SEM_RESSALVAS:true};
fs.writeFileSync(out+'/final-certification.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
