import assert from "node:assert/strict";
import { createHmac, createHash } from "node:crypto";
import { synthesizeVoice, voiceCacheKey } from "../worker/voice-remote-tts.mjs";
const secret = "unit-test-secret-that-is-at-least-32-characters";
const mp3 = new Uint8Array(200); mp3[0] = 0xff; mp3[1] = 0xf3;
const store = new Map();
const kv = { async get(k) { const v = store.get(k); return v ? v.buffer.slice(v.byteOffset, v.byteOffset + v.byteLength) : null; }, async put(k, v) { store.set(k, new Uint8Array(v)); } };
let calls = [];
const okFetch = async (url, init) => {
  calls.push(init);
  const body = Buffer.from(init.body);
  const h = init.headers;
  const msg = ["zevanory-voice-synth-v1", h["x-voice-timestamp"], h["x-voice-nonce"], createHash("sha256").update(body).digest("hex")].join("\n");
  assert.equal(h["x-voice-signature"], createHmac("sha256", secret).update(msg).digest("hex"), "signature matches Render verifier");
  const json = JSON.parse(body.toString());
  assert.equal(json.api_key, "AIza-test"); assert.deepEqual(json.models, ["gemini-3.8-flash-tts", "gemini-3.8-flash-lite-tts"]);
  return new Response(mp3, { status: 200, headers: { "content-type": "audio/mpeg", "x-voice-model": "gemini-3.8-flash-tts" } });
};
const stages = [];
const a = await synthesizeVoice("O combo custa 297 reais.", { apiKey: "AIza-test", kv, secret, fetchImpl: okFetch, onStage: async (s, d) => stages.push([s, d]) });
assert.equal(a.cached, false); assert.equal(a.model, "gemini-3.8-flash-tts"); assert.equal(calls.length, 1);
assert.ok(store.has(await voiceCacheKey("O combo custa 297 reais.")), "mp3 cached");
const b = await synthesizeVoice("O combo custa 297 reais.", { apiKey: "AIza-test", kv, secret, fetchImpl: okFetch });
assert.equal(b.cached, true); assert.equal(calls.length, 1, "cache hit spends no Gemini quota");
await assert.rejects(synthesizeVoice("outro texto", { apiKey: "AIza-test", kv, secret, fetchImpl: async () => new Response(JSON.stringify({ error: "gemini_quota" }), { status: 429 }) }), /^Error: quota$/);
let n = 0;
await assert.rejects(synthesizeVoice("texto 3", { apiKey: "k", secret, fetchImpl: async () => { n++; return new Response("{}", { status: 503 }); } }), /voice_render_http_503/);
assert.equal(n, 1, "server errors never duplicate synthesis or consume quota twice");
await assert.rejects(synthesizeVoice("texto 4", { apiKey: "k", secret, fetchImpl: async () => new Response(new Uint8Array(10), { status: 200 }) }), /invalid_mp3/);
await assert.rejects(synthesizeVoice("texto 5", { apiKey: "", secret, fetchImpl: okFetch }), /gemini_key_missing/);
console.log("VOICE_REMOTE_TTS_TEST=PASS");
