import assert from "node:assert/strict";
import {webcrypto} from "node:crypto";
import {whatsappE2EStatus} from "../worker/whatsapp-e2e-evidence.mjs";
import {handleVoiceAudit} from "../worker/voice-operational-audit.mjs";
globalThis.crypto ||= webcrypto;
const inbound={type:"inbound_processed",message_id:"wamid.real",phone_number_id:"1300972319774588",contact_hash:"owner",queued:false,received_at:"2026-10-04T22:00:00Z",created_at:"2026-10-04T22:00:21Z"};
const voice={type:"outbound_voice",event_id:"wamid.real",provider_message_id:"wamid.voice",contact_hash:"owner",generated_voice:true,created_at:"2026-10-04T22:00:20Z"};
const delivered={type:"delivery",provider_message_id:"wamid.voice",status:"delivered",created_at:"2026-10-04T22:00:20.500Z"};
const status=async events=>whatsappE2EStatus({ZEVANORY_PRIVATE_ARTIFACTS:{list:async()=>({keys:events.map((_,i)=>({name:String(i)})),list_complete:true}),get:async key=>events[Number(key)]}});
assert.equal((await status([inbound,voice,delivered])).e2e,true);
assert.equal((await status([{...inbound,message_id:"internal-audio-test"},voice,delivered])).e2e,false);
assert.equal((await status([inbound,{...voice,event_id:"wamid.other"},delivered])).e2e,false);
assert.equal((await status([inbound,{...voice,contact_hash:"other"},delivered])).e2e,false);
assert.equal((await status([inbound,voice,{...delivered,provider_message_id:"wamid.wrong"}])).e2e,false);
assert.equal((await status([inbound,voice,{...delivered,status:"sent"}])).e2e,false);
assert.equal((await status([{...inbound,phone_number_id:"other"},voice,delivered])).e2e,false);
const bad=await handleVoiceAudit({operation:"audit-encode",pcm_base64:"x",sample_rate:1},{});assert.equal(bad.status,410);
const missing=await handleVoiceAudit({operation:"audit-transcribe",audio_base64:"AAAA"},{});assert.equal(missing.status,503);
console.log("REAL_INBOUND_EXACT_VOICE_DELIVERY_CHAIN_AUDIT_BOUNDARIES=PASS");
const miss=await handleVoiceAudit({operation:'audit-cache',question:'Quanto custa o combo?'},{ZEVANORY_PRIVATE_ARTIFACTS:{get:async()=>null}});
assert.equal(miss.status,200);assert.equal((await miss.json()).skipped,true);
const hit=await handleVoiceAudit({operation:'audit-cache',question:'Quanto custa o combo?'},{ZEVANORY_PRIVATE_ARTIFACTS:{get:async()=>new Uint8Array([0x49,0x44,0x33,...Array(70).fill(0)]).buffer}});
assert.equal(hit.status,200);assert.equal((await hit.json()).voice_cached,true);
const source=await handleVoiceAudit({operation:'audit-source',text:'any'},{});assert.equal(source.status,410);
const {voiceQuality}=await import('./voice_audit_quality.mjs');
assert.equal(voiceQuality('Combo custa 297 reais','Combo custa duzentos e noventa e sete reais').pass,true);
assert.equal(voiceQuality('Combo custa 297 reais','Combo custa 298 reais').pass,false);
assert.equal(voiceQuality('Entrega ocorre por email logo apos o pagamento aprovado','Entrega ocorre por email logo apos o pagamento confirmado').pass,false);
const {readFinalClosure}=await import('./voice_final_closure_read.mjs');
let tries=0;const closure=await readFinalClosure(async()=>++tries===1?new Response('<html>503</html>',{status:503}):Response.json({whatsapp_e2e:true}));
assert.equal(tries,2);assert.equal(closure.whatsapp_e2e,true);
console.log('CACHE_ONLY_NO_SYNTHESIS_NUMERIC_WER_AND_503_RETRY=PASS');
const pair=await crypto.subtle.generateKey({name:'RSA-OAEP',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['encrypt','decrypt']);
const public_key=await crypto.subtle.exportKey('jwk',pair.publicKey);
const keyReq={operation:'audit-encoder-key',public_key,include_gemini:true};
assert.equal((await handleVoiceAudit(keyReq,{ELITE_INTERNAL_TOKEN:'test'})).status,503);
const keyResponse=await handleVoiceAudit(keyReq,{ELITE_INTERNAL_TOKEN:'test',GEMINI_API_KEY:'validated-unit-test-key',GEMINI_FREE_TIER_CONFIRMED:'true'});
const wrappedBody=await keyResponse.json();
assert.equal(JSON.stringify(wrappedBody).includes('validated-unit-test-key'),false);
const unwrapped=await crypto.subtle.decrypt({name:'RSA-OAEP'},pair.privateKey,Buffer.from(wrappedBody.wrapped_gemini_key,'base64'));
assert.equal(new TextDecoder().decode(unwrapped),'validated-unit-test-key');
console.log('VALIDATED_FREE_KEY_RSA_WRAPPING_NO_PLAINTEXT=PASS');
