import assert from "node:assert/strict";
import {webcrypto} from "node:crypto";
import {whatsappE2EStatus} from "../worker/whatsapp-e2e-evidence.mjs";
import {handleVoiceAudit} from "../worker/voice-operational-audit.mjs";
globalThis.crypto ||= webcrypto;
const inbound={type:"inbound_processed",message_id:"wamid.real",phone_number_id:"1300972319774588",contact_hash:"owner",queued:false,received_at:"2026-10-04T22:00:00Z",created_at:"2026-10-04T22:00:21Z"};
const voice={type:"outbound_voice",event_id:"wamid.real",provider_message_id:"wamid.voice",contact_hash:"owner",generated_voice:true,created_at:"2026-10-04T22:00:20Z"};
const delivered={type:"delivery",provider_message_id:"wamid.voice",status:"delivered",created_at:"2026-10-04T22:00:20.500Z"};
const status=async events=>whatsappE2EStatus({ZEVANORY_PRIVATE_ARTIFACTS:{list:async()=>({keys:events.map((_,i)=>({name:String(i)})),list_complete:true}),get:async key=>events[Number(key)]}});
assert.equal((await status([inbound,voice,delivered])).e2e,true);
assert.equal((await status([{...inbound,message_id:"internal-audio-test"},voice,delivered])).e2e,false);
assert.equal((await status([inbound,{...voice,event_id:"wamid.other"},delivered])).e2e,false);
assert.equal((await status([inbound,{...voice,contact_hash:"other"},delivered])).e2e,false);
assert.equal((await status([inbound,voice,{...delivered,provider_message_id:"wamid.wrong"}])).e2e,false);
assert.equal((await status([inbound,voice,{...delivered,status:"sent"}])).e2e,false);
assert.equal((await status([{...inbound,phone_number_id:"other"},voice,delivered])).e2e,false);
const bad=await handleVoiceAudit({operation:"audit-encode",pcm_base64:"x",sample_rate:1},{});assert.equal(bad.status,400);
const missing=await handleVoiceAudit({operation:"audit-transcribe",audio_base64:"AAAA"},{});assert.equal(missing.status,503);
console.log("REAL_INBOUND_EXACT_VOICE_DELIVERY_CHAIN_AUDIT_BOUNDARIES=PASS");
