import { createHmac, timingSafeEqual, createHash } from "node:crypto";

const COOKIE="__Host-zevanory_ref";
const DAYS30=30*86400;
const code=v=>/^[a-z0-9][a-z0-9_-]{2,39}$/i.test(String(v||""))?String(v).toLowerCase():"";
const secret=env=>String(env.AFFILIATE_SIGNING_SECRET||env.OWNER_DASHBOARD_SECRET||"").trim();
const sign=(value,key)=>createHmac("sha256",key).update(value).digest("base64url");
let readyByDb=new Map();

export function referralCookie(ref,env={},now=Date.now()){
 const safe=code(ref),key=secret(env);if(!safe||!key)return null;const payload=`${safe}.${Math.floor(now/1000)}`,value=`${payload}.${sign(payload,key)}`;return `${COOKIE}=${value}; Path=/; Max-Age=${DAYS30}; HttpOnly; Secure; SameSite=Lax`;
}
export function referralFromRequest(request,env={},now=Date.now()){
 const key=secret(env),raw=String(request?.headers?.get?.("cookie")||request?.headers?.cookie||"").split(";").map(x=>x.trim()).find(x=>x.startsWith(`${COOKIE}=`))?.slice(COOKIE.length+1)||"";const [ref,ts,mac]=raw.split(".");if(!key||!code(ref)||!/^\d+$/.test(ts)||Number(ts)*1000<now-DAYS30*1000)return"";const expected=sign(`${ref}.${ts}`,key);try{return expected.length===mac.length&&timingSafeEqual(Buffer.from(expected),Buffer.from(mac))?ref:"";}catch{return"";}
}
async function schema(sql,db){let p=readyByDb.get(db);if(!p){p=(async()=>{await sql.query("create table if not exists affiliate_attributions (order_id uuid primary key,partner_code text not null,amount numeric(12,2) not null,attributed_at timestamptz not null default now(),expires_at timestamptz not null,source text not null default 'ref_cookie')");await sql.query("create table if not exists affiliate_commissions (order_id uuid primary key,partner_code text not null,gross_amount numeric(12,2) not null,commission_rate numeric(5,4) not null default 0.3000,commission_amount numeric(12,2) not null,status text not null default 'pending' check(status in ('pending','confirmed','reversed','paid')),confirmed_at timestamptz null,reversed_at timestamptz null,payout_approved_at timestamptz null,paid_at timestamptz null,updated_at timestamptz not null default now())");})();readyByDb.set(db,p);}await p;}
export async function recordAffiliateAttribution(sql,{databaseUrl="default",orderId,partnerCode,amount}={}){const ref=code(partnerCode),gross=Number(amount);if(!ref||!orderId||!Number.isFinite(gross)||gross<=0)return{recorded:false};await schema(sql,databaseUrl);const rows=await sql.query("insert into affiliate_attributions(order_id,partner_code,amount,expires_at) values($1::uuid,$2,$3,now()+interval '30 days') on conflict(order_id) do nothing returning order_id",[String(orderId),ref,gross]);return{recorded:rows.length===1,partner_code:ref};}
export async function applyAffiliateOrderOutcome(sql,{databaseUrl="default",orderId,event}={}){await schema(sql,databaseUrl);if(event==="payment_confirmed"){const rows=await sql.query(`insert into affiliate_commissions(order_id,partner_code,gross_amount,commission_rate,commission_amount,status,confirmed_at) select order_id,partner_code,amount,0.3000,round(amount*0.30,2),'confirmed',now() from affiliate_attributions where order_id=$1::uuid and expires_at>now() on conflict(order_id) do update set status=case when affiliate_commissions.status='paid' then 'paid' else 'confirmed' end,confirmed_at=coalesce(affiliate_commissions.confirmed_at,now()),updated_at=now() returning order_id,partner_code,commission_amount,status`,[String(orderId)]);return rows[0]||null;}if(event==="refund_confirmed"){const rows=await sql.query("update affiliate_commissions set status=case when status='paid' then status else 'reversed' end,reversed_at=case when status='paid' then reversed_at else now() end,updated_at=now() where order_id=$1::uuid returning order_id,partner_code,commission_amount,status",[String(orderId)]);return rows[0]||null;}return null;}
export async function affiliateReport(env={},sqlFactory){const db=String(env.DATABASE_URL||"");if(!db||!sqlFactory)return{ok:false,reason:"database_unavailable"};const sql=sqlFactory(db);await schema(sql,db);const rows=await sql.query("select status,count(*)::int count,coalesce(sum(commission_amount),0)::text amount from affiliate_commissions group by status order by status");return{ok:true,commission_rate:0.30,attribution_days:30,payout_requires_owner_approval:true,states:rows.map(x=>({status:x.status,count:Number(x.count),amount:Number(x.amount)}))};}
export async function renderAffiliatePanel(env={},sqlFactory){const report=await affiliateReport(env,sqlFactory),rows=(report.states||[]).map(x=>`<tr><td>${x.status}</td><td>${x.count}</td><td>R$ ${x.amount.toFixed(2).replace(".",",")}</td></tr>`).join("");return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="robots" content="noindex"><title>Afiliados · ZEVANORY</title><link rel="stylesheet" href="/admin.css"></head><body><main><h1>Afiliados</h1><p>Atribuição: 30 dias · comissão: 30% · pagamento somente após aprovação do dono.</p><table><thead><tr><th>Estado</th><th>Registros</th><th>Comissão</th></tr></thead><tbody>${rows||"<tr><td colspan=3>Nenhuma comissão registrada.</td></tr>"}</tbody></table></main></body></html>`;}
export function affiliateRecipientHash(value){return createHash("sha256").update(String(value)).digest("hex");}
export function resetAffiliateMemoForTest(){readyByDb=new Map();}
