export const ARBM_ONE_OFFER = Object.freeze({
  id: 'ARBM-ONE',
  product: 'ZEVANORY ONE',
  commercial_name: 'ZEVANORY ONE',
  brand: 'ZEVANORY',
  endorsed_by: 'ZEVANORY',
  brand_signature: 'by ZEVANORY',
  portfolio_role: 'business_operating_system',
  primary: false,
  sellable: false,
  checkout_enabled: false,
  status: 'commercial_model_defined_sales_locked_not_published',
  offer_type: 'saas_subscription',
  delivery_mode: 'managed_service_activation',
  canonical_sha: 'a223603bdb7d060e99fcb9297476216afbd4c9c8',
  pricing: Object.freeze({
    standard_monthly_brl: 697,
    standard_implementation_brl: 1490,
    annual_brl: 6970,
    annual_implementation_brl: 1490,
    enterprise_monthly_from_brl: 1197,
    enterprise_implementation_from_brl: 2490,
  }),
  founder_program: Object.freeze({
    visibility: 'internal_only',
    customer_limit: 5,
    monthly_brl: 497,
    implementation_brl: 990,
    price_protection_months: 12,
  }),
  commercial_rules: Object.freeze({
    charge_per_user: false,
    revenue_share: false,
    lifetime_license: false,
    annual_adjustment: true,
    complex_migration_separately_quoted: true,
    custom_development_separately_quoted: true,
  }),
  commercial_contract: Object.freeze({
    license: 'subscription_per_company_tenant_non_transferable',
    provisioning: 'dedicated_instance_after_payment_and_onboarding_inputs',
    standard_provisioning_target_business_days: 5,
    support_channel: 'suporte@zevanory.api.br',
    critical_incident_initial_response_target_business_hours: 4,
    standard_incident_initial_response_target_business_day: 1,
    availability_target_monthly_pct: 99.9,
    customer_data_export_window_days_after_cancellation: 30,
    third_party_and_scheduled_maintenance_exclusions_apply: true,
  }),
  commercial_release_gate: 'ARBM_ONE_COMMERCIAL_RELEASE_APPROVED',
  sales_gate: 'ZEVANORY_COMMERCIAL_SALES_LOCKED',
  positioning: 'Sistema operacional empresarial integrado para centralizar gestao, PDV, atendimento, delivery, equipe, automacoes e inteligencia.',
});
