export const ARBM_ONE_OFFER = Object.freeze({
  id: 'ARBM-ONE',
  product: 'ARBM ONE',
  commercial_name: 'ARBM ONE - by ZEVANORY',
  brand: 'ZEVANORY',
  endorsed_by: 'ARBM',
  brand_signature: 'by ARBM',
  portfolio_role: 'business_operating_system',
  primary: false,
  sellable: false,
  checkout_enabled: false,
  status: 'commercial_model_defined_sales_locked_not_published',
  offer_type: 'saas_subscription',
  delivery_mode: 'managed_service_activation',
  canonical_sha: '8496cf93cf6aa738d08433d54f5f5cf3c64a16c3',
  pricing: Object.freeze({
    standard_monthly_brl: 697,
    standard_implementation_brl: 1490,
    annual_brl: 6970,
    annual_implementation_brl: 1490,
    enterprise_monthly_from_brl: 1197,
    enterprise_implementation_from_brl: 2490,
  }),
  founder_program: Object.freeze({
    visibility: 'internal_only',
    customer_limit: 5,
    monthly_brl: 497,
    implementation_brl: 990,
    price_protection_months: 12,
  }),
  commercial_rules: Object.freeze({
    charge_per_user: false,
    revenue_share: false,
    lifetime_license: false,
    annual_adjustment: true,
    complex_migration_separately_quoted: true,
    custom_development_separately_quoted: true,
  }),
  sales_gate: 'ZEVANORY_COMMERCIAL_SALES_LOCKED',
  positioning: 'Sistema operacional empresarial integrado para centralizar gestao, PDV, atendimento, delivery, equipe, automacoes e inteligencia.',
});
