import { encryptCommercialSecret, decryptCommercialSecret, newOAuthState, sealOAuthSession, openOAuthSession, assertOAuthState } from './commercialOAuthCrypto.mjs';
export const LINKEDIN_REDIRECT_URI='https://zevanory.api.br/api/oauth/linkedin/callback';
const AUTH='https://www.linkedin.com/oauth/v2/authorization';
const TOKEN='https://www.linkedin.com/oauth/v2/accessToken';
const PROFILE='https://api.linkedin.com/v2/me';
const clean=(v,max=4000)=>String(v??'').trim().slice(0,max);
export function createLinkedInOAuthStart(env=process.env){const client=clean(env.LINKEDIN_CLIENT_ID,200);if(!client)throw new Error('linkedin_client_id_missing');const state=newOAuthState();const url=new URL(AUTH);url.searchParams.set('response_type','code');url.searchParams.set('client_id',client);url.searchParams.set('redirect_uri',LINKEDIN_REDIRECT_URI);url.searchParams.set('state',state);url.searchParams.set('scope','r_liteprofile w_member_social');return {url:url.toString(),cookie:sealOAuthSession({provider:'linkedin',state},env),state};}
export function readLinkedInOAuthCookie(value,state,env=process.env){const p=openOAuthSession(value,env);if(p.provider!=='linkedin')throw new Error('linkedin_oauth_session_invalid');assertOAuthState(p.state,state);return p;}
export async function exchangeLinkedInCode({code,env=process.env,fetchImpl=globalThis.fetch}={}){const client=clean(env.LINKEDIN_CLIENT_ID,200),secret=clean(env.LINKEDIN_CLIENT_SECRET,1000);if(!client||!secret)throw new Error('linkedin_oauth_config_missing');const body=new URLSearchParams({grant_type:'authorization_code',code:clean(code,2000),redirect_uri:LINKEDIN_REDIRECT_URI,client_id:client,client_secret:secret});const r=await fetchImpl(TOKEN,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});const t=await r.json().catch(()=>({}));if(!r.ok||!clean(t.access_token))throw new Error(`linkedin_token_http_${r.status}`);return t;}
export async function fetchLinkedInMe(accessToken,fetchImpl=globalThis.fetch){const r=await fetchImpl(PROFILE,{headers:{authorization:`Bearer ${clean(accessToken)}`,'x-restli-protocol-version':'2.0.0'}});const b=await r.json().catch(()=>({}));if(!r.ok||!clean(b.id,300))throw new Error(`linkedin_me_http_${r.status}`);return {id:clean(b.id,300),authorUrn:`urn:li:person:${clean(b.id,300)}`};}

export async function persistLinkedInCredential(sql,{token,personId,env=process.env}={}){if(!sql?.query)throw new Error('linkedin_sql_required');const expires=Math.max(300,Number(token.expires_in)||5184000);const rows=await sql.query(`insert into provider_oauth_credentials(provider,account_id,access_token_enc,refresh_token_enc,token_type,scope,expires_at,updated_at) values('linkedin',$1,$2,$3,$4,$5,now()+($6::text||' seconds')::interval,now()) on conflict(provider) do update set account_id=excluded.account_id,access_token_enc=excluded.access_token_enc,refresh_token_enc=excluded.refresh_token_enc,token_type=excluded.token_type,scope=excluded.scope,expires_at=excluded.expires_at,updated_at=now() returning account_id,expires_at`,[clean(personId,300),encryptCommercialSecret(token.access_token,env),encryptCommercialSecret(token.refresh_token||'',env),clean(token.token_type,40)||'Bearer',clean(token.scope,1000)||'r_liteprofile w_member_social',String(expires)]);return rows[0];}
export async function loadLinkedInCredential(sql,env=process.env){if(!sql?.query)throw new Error('linkedin_sql_required');const rows=await sql.query("select account_id,access_token_enc,scope,expires_at from provider_oauth_credentials where provider='linkedin' limit 1");const r=rows[0];if(!r)throw new Error('linkedin_oauth_credential_missing');if(new Date(r.expires_at).getTime()<=Date.now()+300000)throw new Error('linkedin_oauth_reauthorization_required');return {...r,access_token:decryptCommercialSecret(r.access_token_enc,env),author_urn:`urn:li:person:${r.account_id}`};}
